### ISSUE TITLE
clashr start fail

### ISSUE THREAD

**Issue by Liuhjhj** [felinae98/clashup#3]
~ >>> systemctl --user start clash                                                                                                                                                                       [1]
Job for clash.service failed because the control process exited with error code.
See "systemctl --user status clash.service" and "journalctl --user -xe" for details.
~ >>> systemctl --user status clash.service                                                                                                                                                              [1]
● clash.service - A rule based proxy in Go.
     Loaded: loaded (/usr/lib/systemd/user/clash.service; disabled; vendor preset: enabled)
    Drop-In: /etc/systemd/user/clash.service.d
             └─clashup.conf
     Active: failed (Result: exit-code) since Fri 2020-12-11 22:44:22 CST; 9s ago
    Process: 20731 ExecStartPre=/usr/bin/clashup --pre (code=exited, status=1/FAILURE)

12月 11 22:44:22 liuhjhj-pc clashup[20731]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
12月 11 22:44:22 liuhjhj-pc clashup[20731]:     return _default_decoder.decode(s)
12月 11 22:44:22 liuhjhj-pc clashup[20731]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
12月 11 22:44:22 liuhjhj-pc clashup[20731]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
12月 11 22:44:22 liuhjhj-pc clashup[20731]:   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
12月 11 22:44:22 liuhjhj-pc clashup[20731]:     obj, end = self.scan_once(s, idx)
12月 11 22:44:22 liuhjhj-pc clashup[20731]: json.decoder.JSONDecodeError: Expecting ':' delimiter: line 12 column 25 (char 584)
12月 11 22:44:22 liuhjhj-pc systemd[3548]: clash.service: Control process exited, code=exited, status=1/FAILURE
12月 11 22:44:22 liuhjhj-pc systemd[3548]: clash.service: Failed with result 'exit-code'.
12月 11 22:44:22 liuhjhj-pc systemd[3548]: Failed to start A rule based proxy in Go..
~ >>>

**Comment by spencerwooo** [comment]
It’s most likely that your configuration file `clashup.json` is written or modified incorrectly.

**Comment by Liuhjhj** [comment]
Thank you very much. I have solved this problem after I check the config file
